# Generated by Django 2.2.6 on 2019-11-03 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallbucket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_up', models.IntegerField(default=0, verbose_name='起床')),
                ('sleep_time', models.IntegerField(default=0, verbose_name='睡眠時間')),
                ('chew_well', models.IntegerField(default=0, verbose_name='咀嚼')),
                ('stretch', models.IntegerField(default=0, verbose_name='ストレッチ')),
                ('exercise', models.IntegerField(default=0, verbose_name='運動')),
                ('good_day', models.IntegerField(default=0, verbose_name='幸福感')),
                ('daily_login', models.IntegerField(default=0, verbose_name='ログイン日数')),
                ('basic_total', models.IntegerField(default=0, verbose_name='基礎点')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
